Java Programs
Ayush-dotcom-hub/PlutoOTTTraning pull request #2
Opened 2023-07-03 16:08 UTC by Ayush-dotcom-hub

2023-07-03 17:43 UTC, bawa-onkar-tft requested changes

2023-07-03 17:43 UTC, bawa-onkar-tft commented on src/ArrayFall.java
> +        int[] positions = {0,1,1,2,3,5,8,13};
@Ayush-dotcom-hub please refer fibonicci java array program on web, than try

right now your logic is wrong

2023-07-03 17:43 UTC, bawa-onkar-tft commented on src/ArraySwap.java
> +        int[] array2 = new int[4];
@Ayush-dotcom-hub right now `new int[4]` is static please make this as dynamic array range

2023-07-03 17:43 UTC, bawa-onkar-tft commented on src/ArraySwap.java
> +
@Ayush-dotcom-hub remove extra spaces

2023-07-05 16:41 UTC, onkarbawa approved these changes

2023-07-11 14:17 UTC, merged